### PR TITLE
Update README.md

### LINKED ISSUE #6: typo in readme misleads regarding integer encoding of hw revision
>balenaFin hardware revision. For balenaFin v1.0 boards the result will be 09 and for v1.0 boards it will be 10, which corresponds to the revision number on the board's QR code.

should be:

```
balenaFin hardware revision. For balenaFin v1.0.0 boards the result will be 09 and for v1.1.0 boards it will be 10, which corresponds to the revision number on the board's QR code.
```

### PR DESCRIPTION
**Pull request by curcuz**
fixes #6

### CODE REVIEW

**Review by chrisys — APPROVED** [review]

**Comment by ntzovanis** [comment]
Lgtm, there is one test failing though.

**Comment by curcuz** [comment]
@majorz @nazrhom can you please look into the rust-test check failing here?

**Comment by majorz** [comment]
@curcuz This is the formatting for Rust code that gives warnings. With Rust before a commit is done `cargo fmt` needs to be run that will automatically format the code. At the other end the CI will test whether it is formatted well and will complain if not so. This is probably caused by difference in versions as not long ago the formatting rules changed often before they were stabilized. I will check now how we can fix this properly.

**Comment by majorz** [comment]
The formatting warnings are gone, but the package does not build because of a dependency update. Will have to fix this one as well.

**Comment by curcuz** [comment]
hey @majorz any chance you have news on this? or who else can I bother?

**Comment by curcuz** [comment]
ping @majorz

**Comment by curcuz** [comment]
ping @majorz

**Pull request merged**
